### ISSUE TITLE
Missing newlines in atom generator

### ISSUE THREAD

**Issue by emsearcy** [certificate-transparency-watch/ct-watch-http-scala#3]
BEGIN and END CERTIFICATE do not currently have newlines separating them from the certificate.

https://github.com/certificate-transparency-watch/ct-watch-http-scala/blob/master/src/main/scala/com/example/DomainAtomFeedGenerator.scala#L27

(I'm currently massaging the data in order to have it be parseable by openssl x509.)

looks like the old version had these:

https://github.com/certificate-transparency-watch/ct-watch-http/blob/master/application.rb#L37

Thanks!

**Comment by tomfitzhenry** [comment]
Thanks for the bug report.

Sorry for the delayed response.

This has been fixed in https://github.com/certificate-transparency-watch/ct-watch-http-scala/commit/57f8f4ac72d3ed786d31c19a693f78a7ae54dc89 , and the RSS feed contains a bunch more info. You should still be able to extract the raw cert, however.
